/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sabirjan_reader_tools_WltDecodeUtil_Wlt2Bmp */

#ifndef _Included_com_sabirjan_reader_tools_WltDecodeUtil_Wlt2Bmp
#define _Included_com_sabirjan_reader_tools_WltDecodeUtil_Wlt2Bmp
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint  JNICALL Java_com_sabirjan_reader_tools_WltDecodeUtil_Wlt2Bmp
        (JNIEnv *, jobject,jbyteArray,jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
